spring.application.name=MusicApp
server.port=2800
spring.docker.compose.file=../docker-compose.yml
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.config.import=optional:file:.env
#spring.datasource.url=${DB_URL}
#spring.datasource.username=${DB_USER}
#spring.datasource.password=${DB_PASS}
#spring.datasource.name=${DB_NAME}
